//File generated by DeviceTypesGenerator
//Any changes will be overwritten

using System;
using System.Collections.Generic;

public enum DeviceType
{
    ANDGate = -173627847,
    Bridge = 1965071259,
    Camera = 1191632477,
    DefaultDevice = 1068489004,
    Door = -2015441228,
    Lamp = -203698500,
    ORGate = -1525939126,
    PowerSource = -1044644846,
    Switch = -937734862,
}

public static class DeviceTypesKeeper
{
    public static readonly Dictionary<DeviceType, Type> ModelTypes = new Dictionary<DeviceType, Type>() 
    {
        { DeviceType.ANDGate, typeof(ANDGateModel) },
        { DeviceType.Bridge, typeof(BridgeModel) },
        { DeviceType.Camera, typeof(CameraModel) },
        { DeviceType.Door, typeof(DoorModel) },
        { DeviceType.Lamp, typeof(LampModel) },
        { DeviceType.ORGate, typeof(ORGateModel) },
        { DeviceType.PowerSource, typeof(PowerSourceModel) },
        { DeviceType.Switch, typeof(SwitchModel) },
    };

    public static readonly Dictionary<Type, DeviceType> ViewTypes = new Dictionary<Type, DeviceType>() 
    {
        { typeof(ANDGateView), DeviceType.ANDGate },
        { typeof(BridgeView), DeviceType.Bridge },
        { typeof(CameraView), DeviceType.Camera },
        { typeof(DoorView), DeviceType.Door },
        { typeof(LampView), DeviceType.Lamp },
        { typeof(ORGateView), DeviceType.ORGate },
        { typeof(PowerSourceView), DeviceType.PowerSource },
        { typeof(SwitchView), DeviceType.Switch },
    };

    public static readonly Dictionary<Type, DeviceType> UIViewTypes = new Dictionary<Type, DeviceType>() 
    {
        { typeof(CameraUIView), DeviceType.Camera },
        { typeof(DefaultDeviceUIView), DeviceType.DefaultDevice },
        { typeof(DoorUIView), DeviceType.Door },
        { typeof(SwitchUIView), DeviceType.Switch },
    };
}
