using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEngine;

public static class DeviceTypesGenerator
{
    public static string EnumName = "DeviceType";
    
    private static string Template =
        $@"//File generated by {nameof(DeviceTypesGenerator)}
//Any changes will be overwritten

using System;
using System.Collections.Generic;

public enum {EnumName}
{{
    #FIELDS#
}}

public static class {EnumName}sKeeper
{{
    public static readonly Dictionary<{EnumName}, Type> ModelTypes = new Dictionary<{EnumName}, Type>() 
    {{
        #MODELS_DICTIONARY_VALUES#
    }};

    public static readonly Dictionary<Type, {EnumName}> ViewTypes = new Dictionary<Type, {EnumName}>() 
    {{
        #VIEWS_DICTIONARY_VALUES#
    }};

    public static readonly Dictionary<Type, {EnumName}> UIViewTypes = new Dictionary<Type, {EnumName}>() 
    {{
        #UI_VIEWS_DICTIONARY_VALUES#
    }};
}}
";

    public static bool Generate()
    {
        Dictionary<string, int> enamValues = new Dictionary<string, int>();
        var modelTypes = AppDomain.CurrentDomain.GetAssignableTypes<DeviceModel>();
        var viewTypes = AppDomain.CurrentDomain.GetAssignableTypes<DeviceView>();
        var uiViewTypes = AppDomain.CurrentDomain.GetAssignableTypes<DeviceUIView>();

        var modelNames = new List<string>();
        var viewNames = new List<string>();
        var uiViewNames = new List<string>();

        foreach (var type in modelTypes)
        {
            enamValues.Add(type.Name.Remove(type.Name.IndexOf("Model")), Animator.StringToHash(type.Name));
            
            modelNames.Add(type.Name.Remove(type.Name.IndexOf("Model")));
        }

        foreach (var type in viewTypes)
        {
            if (!enamValues.ContainsKey(type.Name.Remove(type.Name.IndexOf("View"))))
            {
                enamValues.Add(type.Name.Remove(type.Name.IndexOf("View")), Animator.StringToHash(type.Name));
            }
            
            viewNames.Add(type.Name.Remove(type.Name.IndexOf("View")));
        }

        foreach (var type in uiViewTypes)
        {
            if (!enamValues.ContainsKey(type.Name.Remove(type.Name.IndexOf("UIView"))))
            {
                enamValues.Add(type.Name.Remove(type.Name.IndexOf("UIView")), Animator.StringToHash(type.Name));
            }
            
            uiViewNames.Add(type.Name.Remove(type.Name.IndexOf("UIView")));
        }

        var felds = enamValues.Select(pair => $"{pair.Key} = {pair.Value},").OrderBy(i => i);

        var modelValues = modelNames.Select(name=> $"{{ {EnumName}.{name}, typeof({name}Model) }},").OrderBy(i => i);
        var viewValues = viewNames.Select(name=> $"{{ typeof({name}View), {EnumName}.{name} }},").OrderBy(i => i);
        var uiViewValues = uiViewNames.Select(name=> $"{{ typeof({name}UIView), {EnumName}.{name} }},").OrderBy(i => i);

        string content = Template;

        content = TemplateUtility.ReplaceTagWithIndentedMultiline(content, "#FIELDS#", felds);
        content = TemplateUtility.ReplaceTagWithIndentedMultiline(content, "#MODELS_DICTIONARY_VALUES#", modelValues);
        content = TemplateUtility.ReplaceTagWithIndentedMultiline(content, "#VIEWS_DICTIONARY_VALUES#", viewValues);
        content = TemplateUtility.ReplaceTagWithIndentedMultiline(content, "#UI_VIEWS_DICTIONARY_VALUES#", uiViewValues);
        
        return TemplateUtility.WriteScriptIfDifferent(content, GeneratorLauncher.MakePath(EnumName));
    }

    private static Type[] GetAssignableTypes<T>(this AppDomain domain, bool findGenerics = false)
    {
        var assemblies = domain.GetAssemblies();
        var typeT = typeof(T);
        
        return assemblies
            .SelectMany(a => a.GetTypes())
            .Where(t => !t.IsAbstract && !t.IsInterface && typeT.IsAssignableFrom(t) && t.IsGenericType == findGenerics)
            .ToArray();
    }
}

internal static class TemplateUtility
{
    public static string ReplaceTagWithIndentedMultiline(string templateContent, string tag,
        IEnumerable<string> newLines)
    {
        var tagWithIndentRegex = $"\\ *{tag}";
        var match = Regex.Match(templateContent, tagWithIndentRegex);
        var indent = match.Value.Substring(0, match.Value.Length - tag.Length);
        var replacement = string.Join(Environment.NewLine + indent, newLines);
        return Regex.Replace(templateContent, tag, replacement);
    }

    public static bool WriteScriptIfDifferent(string content, string assetFilePath)
    {
        var fullPath = GetFullPath(assetFilePath);
        var directoryPath = Path.GetDirectoryName(fullPath)!;
            
        if (!Directory.Exists(directoryPath))
            Directory.CreateDirectory(directoryPath);

        if (File.Exists(fullPath) && File.ReadAllText(fullPath) == content)
            return false;

        File.WriteAllText(fullPath, content);
        return true;
    }

    private static string GetFullPath(string fileName) => Path.Combine(Application.dataPath, fileName);
}